-- 1. Insert into PARKING_ZONE
INSERT INTO PARKING_ZONE (ZONE_ID, ZONE_NAME, FLOOR_LEVEL, TOTAL_CAPACITY)
VALUES (1, 'Zone A - Ground Level', 0, 150);

-- 2. Insert into SLOT_TYPE
INSERT INTO SLOT_TYPE (SLOT_TYPE_ID, SLOT_TYPE_NAME, DESCRIPTION)
VALUES (1, 'Compact', 'Designated for standard sedans, hatchbacks, and compact cars');

-- 3. Insert into VEHICLE_TYPE
INSERT INTO VEHICLE_TYPE (TYPE_ID, TYPE_NAME)
VALUES (1, 'Sedan');

-- 4. Insert into PASS_HOLDER
INSERT INTO PASS_HOLDER (MEMBER_ID, MEMBER_NAME, CONTACT_NO, ADDRESS)
VALUES (1, 'John Doe', '+19876543210', '123 Tech Park Residency, Ahmedabad, Gujarat');

-- 5. Insert into MEMBERSHIP_PLAN
INSERT INTO MEMBERSHIP_PLAN (PLAN_ID, PLAN_NAME, DURATION_DAYS, PRICE, DESCRIPTION)
VALUES (1, 'Monthly Unlimited', 30, 2500.00, 'Provides 24/7 unlimited parking access across all standard zones for 30 days');

-- 6. Insert into STAFF_DETAILS
INSERT INTO STAFF_DETAILS (STAFF_ID, STAFF_NAME, DESIGNATION, PHONE_NO, SALARY, DATE_OF_JOINING)
VALUES (1, 'Alex Smith', 'Gate Operator', '+19876500001', 32000.00, '2024-03-01');

-- 7. Insert into PARKING_SLOT
INSERT INTO PARKING_SLOT (SLOT_ID, SLOT_NO, ZONE_ID, SLOT_TYPE_ID, AVAILABILITY_STATUS)
VALUES (1, 'A-G-01', 1, 1, 'OCCUPIED');

-- 8. Insert into PARKING_GATE
INSERT INTO PARKING_GATE (GATE_ID, GATE_NUMBER, GATE_TYPE, ZONE_ID, STATUS)
VALUES (1, 'GATE-IN-01', 'ENTRY', 1, 'ACTIVE');

-- 9. Insert into VEHICLE
INSERT INTO VEHICLE (VEHICLE_ID, REGISTRATION_NO, TYPE_ID, OWNER_NAME, OWNER_PHONE)
VALUES (1, 'GJ-01-AB-1234', 1, 'Jay', '+919876543210');

-- 10. Insert into TARIFF
INSERT INTO TARIFF (TARIFF_ID, TYPE_ID, DAY_TYPE, START_TIME, END_TIME, HOURLY_RATE, OVERTIME_RATE, VALID_FROM, VALID_TO)
VALUES (1, 1, 'WEEKDAY', '08:00:00', '22:00:00', 50.00, 75.00, '2026-01-01', '2026-12-31');

-- 11. Insert into MEMBERSHIP_PASS
INSERT INTO MEMBERSHIP_PASS (PASS_NO, MEMBER_ID, VEHICLE_ID, PLAN_ID, START_DATE, END_DATE, STATUS)
VALUES (1, 1, 1, 1, '2026-08-01', '2026-08-31', 'ACTIVE');

-- 12. Insert into SHIFT_ASSIGNMENT
INSERT INTO SHIFT_ASSIGNMENT (ASSIGNMENT_ID, STAFF_ID, ZONE_ID, GATE_ID, SHIFT_DATE, START_TIME, END_TIME)
VALUES (1, 1, 1, 1, '2026-08-17', '08:00:00', '16:00:00');

-- 13. Insert into PARKING_TICKET
INSERT INTO PARKING_TICKET (TICKET_NO, VEHICLE_ID, SLOT_ID, ENTRY_TIME, ENTRY_GATE_ID, TICKET_STATUS)
VALUES (1, 1, 1, '2026-08-17 09:30:00', 1, 'COMPLETED');

-- 14. Insert into PARKING_EXIT
INSERT INTO PARKING_EXIT (EXIT_ID, TICKET_NO, EXIT_TIME, EXIT_GATE_ID, TOTAL_HOURS, TOTAL_AMOUNT)
VALUES (1, 1, '2026-08-17 12:30:00', 1, 3.00, 150.00);

-- 15. Insert into PAYMENT_DETAILS
INSERT INTO PAYMENT_DETAILS (PAYMENT_ID, EXIT_ID, PAYMENT_MODE, PAYMENT_STATUS, TRANSACTION_TIME, AMOUNT_PAID)
VALUES (1, 1, 'UPI', 'SUCCESSFUL', '2026-08-17 12:31:00', 150.00);